### ISSUE TITLE
undefined symbol: errstart_cold

### ISSUE THREAD

**Issue by k1271697262** [HypoPG/hypopg#76] opened 2022-09-23 07:10 UTC
Hi, I have the same question, did you solve it?
I install the pg_bigm to create index.
It seems that someone install the PG14, but i use
' dpkg -l | grep postgres
sudo apt --purge remove [version-name] ' to remove it .
when i 'sudo pg_config', it seems PG13,but when i create extension.it says 'undefined symbol: errstart_cold'

**Comment by rjuju** [comment] 2022-09-23 07:22
Hi,

Are you saying that you want to compile and install hypopg for pg 13 and that it's failing?

If yes, I think that the issue is that your current user "sees" pg14, and therefore compiles against this version, but you then do `sudo make install`, and sudo "sees" pg13, meaning that you compiled a pg14 hypopg and you install it on pg13, which is the reason of the problem.

You have to make sure that when you compile, when you run `pg_config` you see the same version as with sudo.  You will also probably to do a `make clean` first to force recompilation.

**Comment by k1271697262** [comment] 2022-09-23 07:44
Thank you!
I get the way!
I cd the dir and  run `mkake uninstall ` to un install and then run `make clean `to force recompilation 
Then I try `make`    `make install`  and assign the PG_CONFIG='/usr/bin/pg_config'
The end i create extension successfully

**Comment by rjuju** [comment] 2022-09-23 08:01
Great news!

I'm closing this issue, feel free to open a new one if you face any other problem.

**Closed as completed by rjuju** 2022-09-23 08:01 UTC
Labels: question
