### ISSUE TITLE
Whether support the parallel use when estimated?

### ISSUE THREAD

**Issue by Beliefuture** [HypoPG/hypopg#66] opened 2022-07-19 08:30 UTC
Hi, I am going to using this extension for parallel estimation i.e., create the separate hypothetical index and then get the estimated cost **in each of my test case and in parallel**. But I am not sure whether this extension could support this and whether these parallel test cases would interfere with each other to get the wrong estimation result. Now my method is to create multiple database connect to fulfill this request.

**Comment by Beliefuture** [comment] 2022-07-19 13:16
> Hi,
> 
> This extension supports parallelism. To be more precise, if a regular access method supports parallelism, then an hypothetical index with the same access method will behave the same. It of course requires the same configuration, amount of data in the underlying table, up to date statistics and so on.
> 
> For now, only btree supports parallelism. Here's a naive example:
> 
> ```
> rjuju=# create table t1(id integer, val text);
> CREATE TABLE
> 
> rjuju=# insert into t1 select i, 'val ' || i from generate_series(1, 10000) i;
> INSERT 0 10000
> 
> rjuju=# alter table t1 set (parallel_workers = 2);
> ALTER TABLE
> 
> rjuju=# set parallel_setup_cost = 0; set parallel_tuple_cost = 0;
> SET
> 
> =# vacuum t1;
> VACUUM
> 
> rjuju=# explain select * from t1 join t1 t2 on t1.id = t2.id where t1.id < 100;
>                                    QUERY PLAN
> ---------------------------------------------------------------------------------
>  Gather  (cost=107.60..220.06 rows=99 width=24)
>    Workers Planned: 2
>    ->  Parallel Hash Join  (cost=107.60..220.06 rows=41 width=24)
>          Hash Cond: (t2.id = t1.id)
>          ->  Parallel Seq Scan on t1 t2  (cost=0.00..96.67 rows=4167 width=12)
>          ->  Parallel Hash  (cost=107.08..107.08 rows=41 width=12)
>                ->  Parallel Seq Scan on t1  (cost=0.00..107.08 rows=41 width=12)
>                      Filter: (id < 100)
> (8 rows)
> 
> rjuju=# select hypopg_create_index('create index on t1 (id)');
>     hypopg_create_index
> ----------------------------
>  (13799,<13799>btree_t1_id)
> (1 row)
> 
>  rjuju=# explain select * from t1 join t1 t2 on t1.id = t2.id where t1.id < 100;
>                                                  QUERY PLAN
> ------------------------------------------------------------------------------------------------------------
>  Gather  (cost=9.70..122.17 rows=99 width=24)
>    Workers Planned: 2
>    ->  Parallel Hash Join  (cost=9.70..122.17 rows=41 width=24)
>          Hash Cond: (t2.id = t1.id)
>          ->  Parallel Seq Scan on t1 t2  (cost=0.00..96.67 rows=4167 width=12)
>          ->  Parallel Hash  (cost=9.19..9.19 rows=41 width=12)
>                ->  Parallel Index Scan using "<13799>btree_t1_id" on t1  (cost=0.04..9.19 rows=41 width=12)
>                      Index Cond: (id < 100)
> (8 rows)
> ```
> 
> > Now my method is to create multiple database connect to fulfill this request.
> 
> I'm not quite sure what you mean. If you mean having different connections for each tests then it's the best approach. Hypothetical indexes only exist in a connection local memory, so two different connection will never be able to use each other hypothetical indexes.


Hi, thanks for your reply. But I think you might misunderstand the meaning of the "parallelism" that I said. Apology for the unclear statement.

In my setting, I want to issue a number of the queries to get the estimated cost under the simulation of the hypothetical index extension **simultaneously**.  And that's what I refer to "parallelism" is. 

And the solution I come across is to set up the multiple connections in the meanwhile, which seems to not interfere each other as you mentioned. But I want to figure out whether there are any method to implement it i.e., I want acquire the set of the estimated cost together.

> Hypothetical indexes only exist in a connection local memory, so two different connection will never be able to use each other hypothetical indexes.

**Comment by rjuju** [comment] 2022-07-19 13:34
> Hi, thanks for your reply. But I think you might misunderstand the meaning of the "parallelism" that I said

Oh ok, indeed I wasn't sure if the cost was also related to postgres parallelism :)

> And the solution I come across is to set up the multiple connections in the meanwhile, which seems to not interfere each other as you mentioned. But I want to figure out whether there are any method to implement it i.e., I want acquire the set of the estimated cost together.

Right.  Do you have a bit more details about the processing?  For instance hypothetical indexes are only automatically destroyed when the postgres backend process exists, so if you reuse some of the connections during the process you might have more hypothetical indexes than expected.

That shouldn't be a problem if you process a different set of tables, unless you create a lot of hypothetical indexes (see for instance https://github.com/HypoPG/hypopg/issues/65 where OP hit a hard limit on the number of concurrent hypothetical indexes in the same connection).

**Comment by Beliefuture** [comment] 2022-07-19 14:54
@rjuju Hi, thanks for your reply.

Actually, I attempt to connect the Postgresql through _psycopg2_ in Python script. Then I encapsulate the execution SQL statement in Python to get the estimated cost. As I have a number of queries to test, I want to get the estimated result **more efficiently i.e. in parallel.** 

I do notice that the hypothetical index created was dropped automatically after the database connection existed. But I am not so sure whether build the multiple connection to do the hypothetical index simulation will affect the estimated cost i.e. whether these connections are independent or isolated. Indeed, I am not so aware of the mechanism of the HypoPG.

> For instance hypothetical indexes are only automatically destroyed when the postgres backend process exists.

And I only access certain database i.e. there might be overlapped tables when simulation.

> That shouldn't be a problem if you process a different set of tables.

As for the problem metioned in https://github.com/HypoPG/hypopg/issues/65, I think the actual assignment of the oid (not so aware of the function of real oid) might not influence the estimated result and I am not going to use it.

> unless you create a lot of hypothetical indexes (see for instance https://github.com/HypoPG/hypopg/issues/65 where OP hit a hard limit on the number of concurrent hypothetical indexes in the same connection).

**Comment by rjuju** [comment] 2022-07-19 17:01
> Actually, I attempt to connect the Postgresql through psycopg2 in Python script. Then I encapsulate the execution SQL statement in Python to get the estimated cost

I see.  FTR that's actually exactly what the global index advisor is doing in the powa-web project, and I confirm that it works fine.

> As for the problem metioned in https://github.com/HypoPG/hypopg/issues/65, I think the actual assignment of the oid (not so aware of the function of real oid) might not influence the estimated result and I am not going to use it.

The "real oid" use real oid, ie. in the same range as what you would get with a normal index.  It's not that expensive, but it requires to do a write and thus cannot work on a physical standby node.

The default "fake oid" use a range of oid that should never be used on a given instance, and can be used on a standby node, but that range is about ~2500 values.  So if you try to have more than ~2500 hypothetical index created in a single connection, it will error out when trying to create a new one.  Hopefully your approach won't require to create that many hypothetical indexes, but I just thought it was worth noting especially if you reuse connection and don't drop the hypothetical across reuse.

**Comment by Beliefuture** [comment] 2022-07-20 02:44
@rjuju Hi, thanks for your explanation.

I find `the powa-web project`  you mentioned is another project you maintained and it seems like serve as a performance monitor of the corresponding database.

> FTR that's actually exactly what the global index advisor is doing in the powa-web project, and I confirm that it works fine.

Does it make no difference between the use of `fake oid` and `real oid` if I don't create more than 2500 hypothetical index in a single connection? Actually, I create a connection instance for each query through `psypopg.connect(**args)` function and I think they might not interfere each other among these connections. And the connections are destroyed automatically after the termination of the program.

> Hopefully your approach won't require to create that many hypothetical indexes, but I just thought it was worth noting especially if you reuse connection and don't drop the hypothetical across reuse.

I still attempt to find a efficient way to get the estimated cost of my multiple queries.

**Comment by rjuju** [comment] 2022-07-20 03:01
> Does it make no difference between the use of fake oid and real oid if I don't create more than 2500 hypothetical index in a single connection? 

real oids won't work on a standby node.  Apart from that as long as you work on a primary node, the behavior should be the same, with one exception:  if you have an incredible large number of objects (close to 2^32), the number of real oid that can still be used will be small (possibly smaller than the number of fake oids), and it then becomes possible that the oid that was assigned to a hypothetical index is then used by a real object, for instance if you create a real index or a new relation.  If that happens you may have unreliable behavior.

The same thing is also possible if you have a small number of object but oid keeps being generated.  For instance if some application creates and drops billions of temp tables, or of hypothetical indexes.

**Comment by Beliefuture** [comment] 2022-07-20 07:20
@rjuju Hi.

So there are two conditions that will cause the exception.

1) `real oid`: the number of the actual index created is large enough i.e. 2^32 so that the number of the real oid assigned to the hypothetical index will be quite small and will lead to overlapped oid will the actual index.

2) `fake oid`: the number of the hypothetical index created is large enough i.e. > 2500.

The default configuration is the `fake oid`. So if I avoid the circumstances above, I build multiple DB connections to get the estimated cost in parallel, is it all right?

To be specific, these estimation processes are isolated among connections?

**Comment by rjuju** [comment] 2022-07-20 07:37
I think there's some misunderstanding on how oids work with postgres.  Just to be clear, oids are 32b unsigned integers, and objects created at runtime get values between 16384 and 2^32-1.  Those have to be unique inside the same catalog (e.g. pg_class), but oids are generated sequentially for all catalogs.

So if you create a table with a single column, you will generate multiple consecutive oids, even if the column and the table could have the exact same oid without being a problem.

Then that counter can wraparound, and starts again at 16384.  When you need a new oid, postgres simply increase the current counter and check if that oid is already in use for the needed catalog, and keep increasing the value until it finds a "free" value.

So, for real oids, the problem isn't the number of actual indexes, it's whether the oid that was generated when creating a hypothetical indexes has since been given to another object, or worse another index.  It usually doesn't happen because usually people don't have billions of objects and/or don't create /drop billions of objects (or other hypothetical indexes), but if that's your case you have to be careful (and probably keep using fake oids, since those will never be used by real objects).

For fake oid, they're generated in the same way, with possible wraparound, except that the range is between ~14000 (the highest existing oid that's below 16384) and 16384, and that only hypopg will use those values (or possibly other extensions, but I don't know any).  So the problem isn't to create more than ~2500 hypothetical indexes, it's to have more than ~2500 hypothetical indexes at the same time within a single connexion.  You can create and drop billions of hypothetical indexes, even in the same connexion, without any problem as long as there are no more than ~2500 at the same time in the same connexion.  If two connections have a hypothetical index with the same oid, it's not a problem because they won't see each other.

**Comment by Beliefuture** [comment] 2022-07-20 08:20
@rjuju Hi.

Thanks for your detailed explanation. I try to list my understanding below.

1. `oid` is a unique identifier used in Postgresql to identify the object (not only the index) in database.

2. the counter of `oid`  is reset to start from 16384 sometime when assign a new "free" `oid` to the new object created. Actually, I notice the `oid` (fake) value returned by the `hypopg_create_index()` function is consecutive when I build a set of  hypothetical indexes successively but just starts from different value.

> When you need a new oid, postgres simply increase the current counter and check if that oid is already in use for the needed catalog, and keep increasing the value until it finds a "free" value.

3. there may exist `oid` collision in Postgresql, which may leads to exception but seldom happens only when billions of objects existed.

4. certain range of the value on `oid` (fake) is reserved for Hypopg and other extensions.

5. no more than ~2500 at the same time in the same connection will be fine.

There is one last thing I don't understand that the difference between the function of `real oid` and `fake oid` when using the Hypopg extension except the `real oid` won't work on a standby node as you mentioned. In other words, why not only use `fake oid`, which seems to be safer?

**Comment by Beliefuture** [comment] 2022-07-20 09:13
@rjuju 

Thanks for your detailed explanation. I will go further testing on my case. Best :).

**Comment by rjuju** [comment] 2022-07-20 09:35
Ok :) I'm closing this issue for now, feel free to reopen it or create a new one if you have any other question!

**Closed as completed by rjuju** 2022-07-20 09:35 UTC
Labels: question
