### ISSUE TITLE
After creating the index, use the explain command to report an error.

### ISSUE THREAD

**Issue by Liebesleid-z** [HypoPG/hypopg#80] opened 2023-06-26 09:23 UTC
-- create  test table
create table test_st2(id int);  
insert into test_st2 select generate_series(1,1000000); 
-- ceate index
select monitor.hypopg_create_index('CREATE INDEX idx_test_st2_id ON public.test_st2 USING btree (id)');
`(13741,<13741>btree_test_st2_id)`
-- execute explain
explain (FORMAT JSON) select * from test_st2 where id=9280;
`ERROR:  cache lookup failed for index 13740`

**Comment by Liebesleid-z** [comment] 2023-06-26 09:58
I was fine yesterday, but when I executed it again today, I suddenly reported an error.

**Comment by Liebesleid-z** [comment] 2023-06-26 10:01
Do you have any ideas to locate the problem?

**Comment by rjuju** [comment] 2023-06-26 10:16
Not really.  As far as I know the only way to get such an error would be to force a plan using an existing hypothetical index to be cached, then removing this hypothetical index and then try to explain that prepared statement again.  That clearly can't be the case since you're referencing a newly created table.

Another way would be to create a table and a hypothetical index, then drop the table and then create a new table long enough after the drop so that enough oid are consumed and your new table gets the same oid as the one that were dropped.  But it seems quite unlikely as you either need to have close to 4 billions objects in your database or create close to 4 billions new object before or a mix of those.

Both scenario are somewhat out of scope for this project and more of a "don't do that", as trying to properly implement a cache to make sure that hypothetical indexes are automatically dropped when the underlying table is dropped, but only if the (sub) transaction is committed would require a lot of effort for scenarios that shouldn't happen.

**Comment by Liebesleid-z** [comment] 2023-06-26 10:17
I found that this problem will definitely occur after I update the image.
I updated and did these operations in the new image.
``` shell
mkdir -p /usr/lib/postgresql/14/lib/bitcode/pg_qualstats
cp /usr/lib/postgresql/14/lib/bitcode/pg_qualstats.bc  /usr/lib/postgresql/14/lib/bitcode/pg_qualstats/pg_qualstats.bc
```

**Comment by rjuju** [comment] 2023-06-26 10:21
I'm not sure how changing something related to pg_qualstats would matter.  Did you really only do that or change other stuff, including related to hypopg?

**Comment by Liebesleid-z** [comment] 2023-06-26 10:22
postgres=# drop extension hypopg;
DROP EXTENSION
postgres=# create extension hypopg
postgres-# ;
CREATE EXTENSION
postgres=# drop table test_st2;
DROP TABLE
postgres=# create table test_st2(id int);
CREATE TABLE
postgres=# insert into test_st2 select generate_series(1,1000000);
INSERT 0 1000000
postgres=# select hypopg_create_index('CREATE INDEX idx_test_st2_id ON public.test_st2 USING btree (id)');
       hypopg_create_index
----------------------------------
 (13740,<13740>btree_test_st2_id)
(1 row)

postgres=# explain (FORMAT JSON) select * from test_st2 where id=9280;
ERROR:  cache lookup failed for index 13740
postgres=# create table test_st1(id int);
CREATE TABLE
postgres=# insert into test_st1 select generate_series(1,1000000);
INSERT 0 1000000
postgres=# select hypopg_create_index('CREATE INDEX idx_test_st1_id ON public.test_st1 USING btree (id)');
       hypopg_create_index
----------------------------------
 (13741,<13741>btree_test_st1_id)
(1 row)

postgres=# explain (FORMAT JSON) select * from test_st1 where id=9280;
ERROR:  cache lookup failed for index 13741

**Comment by Liebesleid-z** [comment] 2023-06-26 10:25
> I'm not sure how changing something related to pg_qualstats would matter. Did you really only do that or change other stuff, including related to hypopg?


I really only changed it here. Is it related to the storage of the Docker environment?

**Comment by rjuju** [comment] 2023-06-26 10:34
I don't know much about docker storage.

The .bc file are for the jit feature, so it seems a bit surprising that it would cause such a problem.  Still I don't know what would happen if you add a new .bc file while postgres is running.  Was all of it done using the same connection or did you open a new session each time?

Can you reproduce after restart the container and/or recreating a proper image?

**Comment by Liebesleid-z** [comment] 2023-06-26 12:14
I tried to deploy the old version of the image and the new version of the image in two new environments, both of which can be used normally.

And the same upgrade operation for the old version can also be used normally.

But I can't fix the environment where I reported an error. I'm in pain.

**Comment by rjuju** [comment] 2023-06-26 12:19
As far as I know any modification done in the container filesystem (as in not a folder that's behind a docker volume) isn't persistent, so a restart of the container should revert it to it's original state?

**Comment by Liebesleid-z** [comment] 2023-06-26 12:24
I'm not modifying the image, I'm building a new image on the basis of the old image.

**Comment by rjuju** [comment] 2023-06-26 13:24
I'm not sure what to tell you.  It seems to be caused by something you did on a container image more than a bug in hypopg, so I don't think I can help you.

**Closed as not planned** 2023-06-29 06:05 UTC
